version: 0.2

run-as: root

phases:
  install:
    run-as: root
    runtime-versions:
      python: 2.7
    commands:
      - "pip install -r flask/requirements.txt"
      # - "python flask/db.py"