version: 0.2

run-as: root

phases:
  install:
    run-as: root
    runtime-versions:
      python: 3.8
    commands:
      - "pip install -r django/requirements.txt"
      - "pip install psycopg2"
      # - "./django/notejam/manage.py syncdb"
      - "./django/notejam/manage.py migrate"